### ISSUE TITLE
python basecrack.py -h fail

### ISSUE THREAD

**Issue by DLTech21** [mufeedvh/basecrack#11]
Traceback (most recent call last):
  File "basecrack.py", line 11, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by mufeedvh** [comment]
You have to install the dependencies first.

    $ pip install -r requirements.txt

**Comment by DLTech21** [comment]
already install, still run error

**Comment by DLTech21** [comment]
![image](https://user-images.githubusercontent.com/2238211/115672340-0c26ac80-a37e-11eb-8ccf-81d8c7e517f3.png)

**Comment by DLTech21** [comment]
solved by running python3 basecrack.py -h
