### ISSUE TITLE
对一些有特殊字符的base编码无法解码

### ISSUE THREAD

**Issue by tysmlq** [mufeedvh/basecrack#13]
使用中发现，如果编码中存在特殊字符（#!@"":)时，即使是base85编码也无法解码。
比如：
1cI9M2)-sF1h8IP1bppJ1cR<H1G^jE2)-q!1h/?t1cI7%2.8@!1hJRU1bppI1h8F'1GUdG1h&:Q1G^jC1cI9L1GgsG1hJU*1gr7!1h8I$1GUdD1hJRU1gr6s1cI7%2*!KM1h&=&1gr7"1cI9H1GUgE2)@("2.8@#1cI9L1GgsG1h8IP1bppG1cI9L1G^mI1c$t"1gr7M1cI9L1GUdD1c[ER1gr7#1h8F#1GUdG1h&:Q2)I-F1cI9H1GgsG1hJU*1gr7"1h8F#1G^jH1c[C(1bpps1cI7%2*!NN1h&:R1gr7"1cI3I1GUgE2)@(#1G^jC1cI9I2)@*H1c[C(2.8@"1h8I$1G^jH1c$t"1gr7M1cI:#2)@'G1h&:Q1gr7$1cR<H1GUdG1c[C(1bppK1cI7%2*!KM1cI:#1bgds

**Comment by mufeedvh** [comment]
Is this valid Base85? Can you please send this encoded string on Pastebin or a Gist?

**Comment by tysmlq** [comment]
It's valid,but exist some special char,so many base85-decoder can't decode correctly,but some tool can do.
for examlpe，https://www.qtool.net/baseencode
plain text of above strings is :
475651544d5a425848413344514e4c42474d5a544f4e42574d4932474b4e3342475534544f594a554d5532444f4e4a52474d59444b594a5647513254534d5a56475534544d5a425547553357434e4a5a4755324449594a574d4532474b4e5442475134544f594a564d453347494e425a474d59544b4f4a5647343254534e334247525354494e5a554d553347434e4a5a475a53444b4e4a5848413247494e4259474d5944475a413d

**Comment by mufeedvh** [comment]
It seems to work with the valid Ascii85 spec. This is derived from the given plain text by encoding it on https://www.qtool.net/baseencode.

```
1cI9M2)-sF1h8IP1bppJ1cR<H1G^jE2)-q!1h/?t1cI7%2.8@!1hJRU1bppI1h8F'1GUdG1h&:Q1G^jC1cI9L1GgsG1hJU*1gr7!1h8I$1GUdD1hJRU1gr6s1cI7%2*!KM1h&=&1gr7"1cI9H1GUgE2)@("2.8@#1cI9L1GgsG1h8IP1bppG1cI9L1G^mI1c$t"1gr7M1cI9L1GUdD1c[ER1gr7#1h8F#1GUdG1h&:Q2)I-F1cI9H1GgsG1hJU*1gr7"1h8F#1G^jH1c[C(1bpps1cI7%2*!NN1h&:R1gr7"1cI3I1GUgE2)@(#1G^jC1cI9I2)@*H1c[C(2.8@"1h8I$1G^jH1c$t"1gr7M1cI:#2)@'G1h&:Q1gr7$1cR<H1GUdG1c[C(1bppK1cI7%2*!KM1cI:#1bgds
```

![Screenshot from 2021-09-06 19-24-28](https://user-images.githubusercontent.com/26198477/132227967-886a6170-e91c-4b4f-bb5f-5c942ea67833.png)
