### ISSUE TITLE
Include new feature

### ISSUE THREAD

**Issue by WeichuZheng** [mufeedvh/basecrack#14]
Are you interested in including Base100 to your work? Or you regard it as a king of trick that differs from traditional base codes?

**Comment by mufeedvh** [comment]
You mean [this](https://github.com/AdamNiederer/base100)? Haha that would be interesting to work on although will not be useful in any regard. If I do get some time, I will maybe add it as an additional option. This tool is basically meant to solve lame CTF challenges and who knows if some CTF comes up with Base100 in a challenge, might as well add that too lol.

**Comment by WeichuZheng** [comment]
> You mean [this](https://github.com/AdamNiederer/base100)? Haha that would be interesting to work on although will not be useful in any regard. If I do get some time, I will maybe add it as an additional option. This tool is basically meant to solve lame CTF challenges and who knows if some CTF comes up with Base100 in a challenge, might as well add that too lol.

Actually I also participate in some CTF events, and I've met Base100 many times in others' summary on crypto questions as 'emoji code'. Adding it to your work might be a funny and useful option lol.

**Comment by mufeedvh** [comment]
Yeah that would be funny :laughing:, I will definitely add Base100 soon. Also, if you know any other challenges like these please do mention them so I can automate that too lol. These kinda challenges are getting out of hand.

**Comment by mufeedvh** [comment]
Hey @Phile-matology, I added it!

Lo and behold! :laughing: 

![base100](https://user-images.githubusercontent.com/26198477/132130904-6166eeef-b4d0-445b-b563-a8bc1cce7adf.png)


**Try it out!**

    $ git pull
    $ pip3 install -r requirements.txt
    $ python3 basecrack.py

Base100 Encoded String
```
👫👟👜🐗👨👬👠👚👢🐗👙👩👦👮👥🐗👝👦👯🐗👡👬👤👧👜👛🐗👦👭👜👩🐗👫👟👜🐗👣👘👱👰🐗👛👦👞🐁
```

Along with this addition and some refactoring is the `v4.0` release! :raised_hands:
