### ISSUE TITLE
hi，I encountered "!" when decoding base85

### ISSUE THREAD

**Issue by Joackk** [mufeedvh/basecrack#17]
If there is a "!" in the "shell" you will get this error
![image](https://user-images.githubusercontent.com/45162558/159872155-87df36a2-6549-44e3-98e1-6cb364349542.png)
And to avoid this mistake is to give "!" with "\", but then it will not be decoded properly
![image](https://user-images.githubusercontent.com/45162558/159872406-f5987c8d-4f89-42b8-a259-e6977d74b093.png)

**Comment by Joackk** [comment]
It turned out because bash can't appear "!"

**Comment by Joackk** [comment]
Using online tools he was successful
![image](https://user-images.githubusercontent.com/45162558/159873811-8bece4f6-c0e9-47ab-a9c5-883ace263d6f.png)
But the tool still says this is an invalid code, what is the problem?
![image](https://user-images.githubusercontent.com/45162558/159874108-f7ef0172-d9d9-425f-a790-c79745816162.png)

**Comment by mufeedvh** [comment]
Hey, sorry for the late response. Can you please attach the encoded string so that I can debug the issue. Thank you for raising the issue! :raised_hands:
